// Code generated by gen/context_paths. DO NOT EDIT.
package middleware

var contextSkipPathsPrefix = []string{
	"GET /api/context/app",
	"GET /api/healthz",
	"HEAD /api/healthz",
	"GET /api/oauth/url",
	"GET /api/oauth/callback",
	"POST /api/oidc/token",
	"GET /api/oidc/userinfo",
	"POST /api/oidc/userinfo",
	"GET /resources",
	"POST /api/user/login",
	"GET /.well-known/openid-configuration",
	"GET /.well-known/jwks.json",
	"GET /.well-known/webfinger",
}
